name: daily builds

on:
  workflow_dispatch:
  schedule:
    # Run once daily at 00:00 UTC, ~7/8PM CST
    - cron: "0 0 * * *"

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sandbox:
          [
            react/latest/react-18-vite,
            react/latest/react-17-vite,
            react/latest/react-16-vite,
            react/v10/react-17-vite,
            react/v10/react-16-vite,
          ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Use Node.js 18.x
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: |
          cd ${{ matrix.sandbox }}
          yarn install
      - name: Build project
        run: |
          cd ${{ matrix.sandbox }}
          yarn build
