name: daily builds

on:
  schedule:
    # Run once daily at 00:00 UTC, ~7/8PM CST
    - cron: "0 0 * * *"

jobs:
  builds:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        sandbox:
          [
            react/latest/react-18-vite,
            react/latest/react-17-vite,
            react/latest/react-16-vite,
            react/v10/react-17-vite,
            react/v10/react-16-vite,
          ]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3
      - name: Use Node.js 18.x
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d #v3.8.1
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: |
          cd ${{ matrix.sandbox }}
          yarn install
      - name: Build project
        run: |
          cd ${{ matrix.sandbox }}
          yarn build
